CREATE TABLE IF NOT EXISTS CONFIG (
  CONFIG_KEY VARCHAR(128) PRIMARY KEY,
  CONFIG_VALUE VARCHAR(512));

CREATE TABLE IF NOT EXISTS EVENTS (
  id          MEDIUMINT    NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(256) NOT NULL,
  description TEXT,
  start_time  DATETIME,
  finish_time DATETIME,
  image_url   VARCHAR(128)
);

DROP TABLE EVENTS